### ISSUE TITLE
Error - The 'MSOLAP.8' provider is not registered on the local machine

### ISSUE THREAD

**Issue by Mike-Honey** [ladataweb/data-quality-report#1]
After the credentials pop-up, the refresh starts, but then every query returns this error:

An error happened while reading data from the provider: 'The 'MSOLAP.8' provider is not registered on the local machine.'

Am I missing something? Windows 11 laptop with typical Office etc installed.

**Comment by Mike-Honey** [comment]
I found this blog post:
https://powerusers.microsoft.com/t5/Power-Query/HELP-The-MSOLAP-8-provider-is-not-registered-on-the-local-machin/m-p/1069807/highlight/true

... which pointed at the download page for the "Analysis Services client libraries"
https://learn.microsoft.com/en-us/analysis-services/client-libraries?view=asallproducts-allversions&viewFallbackFrom=sql-server-2017

Installing these seemed to get past this roadblock.

If this is correct, perhaps note in the README?

**Comment by ibarrau** [comment]
Hi. Thanks for reaching. I'm sorry it took a long time. I didn't receive a notification until the second comment. Sure we can add it at readme. Again sorry we couldn't help and thank you so much for helping to improve our tool :)
