### ISSUE TITLE
Query: The Measures throws: A cyclic reference was encountered during evaluation

### ISSUE THREAD

**Issue by Mike-Honey** [ladataweb/data-quality-report#2]
I'm getting to the point where the PBIT is trying to refresh. But my refresh is blocked by this error:

The Measures

A cyclic reference was encountered during evaluation

After closing that message, the PBIT tables appear, and I can Apply Changes to load the data successfully.

**Comment by ibarrau** [comment]
Hi. If your dataset is sample or non sensitive data, can you share it with us? because we can't reproduce it. It just works for us.

**Comment by Mike-Honey** [comment]
I've been using this tool a bit more on the same dataset and it has been working smoothly.
