### ISSUE TITLE
Errors for the Quartile columns from GetPercentile Query - possibly triggered by TableName values with embedded spaces

### ISSUE THREAD

**Issue by Mike-Honey** [ladataweb/data-quality-report#3]
My refresh threw a few error rows for the Quartile columns in the Profiles query.

Here's the Error details for one cell:

An error occurred in the ‘GetPercentile’ query. DataSource.Error: OLE DB: Query (1, 72) The syntax for 'Data' is incorrect. (EVALUATE SELECTCOLUMNS('Sample Data', "Sample Data[unitPrice]", Sample Data[unitPrice])).

It reads like the 2nd and 3rd references to table 'Sample Data' are not surrounded by single quotes?

The errors only occurred when the TableName column values had embedded spaces (e.g. 'Sample Data').

**Comment by ibarrau** [comment]
Hi. Thanks for the comment. What do you mean it occurs when values has spaces? I'm testing using spaces in the columns or in the tables and it works. Do you have any other special character at the name?

**Comment by Mike-Honey** [comment]
I've been using this tool a bit more on the same dataset and it has been working smoothly.
